plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0' // Spring Boot 버전 3.4.0으로.
    id 'io.spring.dependency-management' version '1.1.0'
}

group 'me.yjyang'
version '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17) // java는 oracle jdk 17
    }
}


repositories {
    mavenCentral()
}


dependencies {
    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-web'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher' // 1001 추가
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // 스프링 데이터 JPA
        runtimeOnly 'com.h2database:h2' // 인메모리 데이터베이스
        compileOnly 'org.projectlombok:lombok' // 반복적인 메서드 작성 작업을 줄여주는 롬복
        annotationProcessor 'org.projectlombok:lombok'
    }
}


test {
    useJUnitPlatform()
}